---
title: "Repeated Measures ANOVA Length Frequency"
author: "Alex J. Benecke"
date: "February 9, 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup load required packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(FSA)
library(magrittr)
library(dplyr)
library(plotrix)
library(Matching)
library(sciplot)
```


### PSD-X 2013 - 2016 CPUE

```{r}
cpe <- read.csv("Data/Clean-Data/CPUE-gcat_2013-2016.csv") %>%
  filterD(Species == 317) %>%
  filterD(gcat != "substock") %>%
  filterD(!is.na(gcat))

headtail(cpe)
str(cpe)

bargraph.CI(cpe$Year, cpe$cpe.hr)

cpe2 <- aggregate(cpe.hr ~ Year + gcat, data = cpe, FUN = mean)

cpe2


bargraph.CI(cpe2$Year, cpe2$cpe.hr)

```



```{r Create new gcatQ variable Grouping Q- and Q+ 2013-16}
levels(cpe$gcat)

cpe %<>% mutate(gcatQ=mapvalues(gcat,
                                 from=c("stock","quality","preferred", "memorable", "trophy"),
                                 to=c("quality-", "quality+", "quality+", "quality+", "quality+")),
                 gcatQ=droplevels(gcatQ))

headtail(cpe)

bargraph.CI(cpe$Year, cpe$cpe.hr)


aov1 <- aov(cpe.hr~gcatQ+Year,data = cpe)

summary(aov1)

cpe3 <- aggregate(cpe.hr ~ Year + gcatQ, data = cpe, FUN = mean)

cpe3


aov2 <- aov(cpe.hr~gcatQ+Year,data = cpe3)

summary(aov2)


bargraph.CI(cpe3$Year, cpe3$cpe.hr)

```  


```{r }
library(nlme)

headtail(cpe)

lme1 <- lme(cpe.hr~gcatQ, data = cpe, random = ~1 | Year)

summary(lme1)



XvY <- ifelse(cpe$gcat=="quality",1,0) +
  ifelse(cpe$gcat=="preferred",1,0) +
  ifelse(cpe$gcat=="memorable",1,0) +
  ifelse(cpe$gcat=="trophy",1,0) +
  ifelse(cpe$gcat=="stock",-1,0)

XvY

lme2 <- lme(cpe.hr~XvY, data = cpe, random = ~1 | Year)

summary(lme2)
```




















