---
title: "Von Bertalanffy GM No Sex Term"
author: "Alex Benecke"
date: "July 8, 2017"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(FSA)
library(tidyverse)
library(nlme)
```
```{r Load and Prep Data}
LMBL <- read.csv("Data/Clean-Data/2016_largemouth-bass_long-format.csv") %>%
  select(FID:BI.len) %>%
  arrange(FID,Agei)

### Making factors factors
LMBL$FID <- factor(LMBL$FID)
LMBL$Site <- factor(LMBL$Site)
LMBL$SEXCON <- factor(LMBL$SEXCON)
LMBL$Sex <- factor(LMBL$Sex)
```
```{r Display data}
str(LMBL)
headtail(LMBL)
```

```{r Group Data}
datgr = groupedData(BI.len ~ Agei|FID, data = LMBL,
                  labels = list(x = "Age", y = "Size"),
                  units = list(x = "(Years)", y = "(mm)"))
```

Creating the von Bertalanffy function.

```{r Build von Bertalanffy Growth Model}
LVB <- function(x, Linf, K, t0){
  y = Linf * (1 - exp(-K * (x - t0)))
  y
}
LVB <- vbFuns()

LVB(5, 422.8, 0.39, -0.40)
LVB(5, Linf = c(422.8, 0.39, -0.40)) ### Should be the same output
```


### nlme mod (No Sex Term)

```{r SexMod0, eval=FALSE}
nlme.mod <- nlme::nlme(BI.len ~ LVB(Agei, Linf, K, t0), data = datgr,
                            fixed = list(Linf ~ 1, K ~ 1, t0 ~ 1),
                            random = Linf+K+t0 ~ 1,
                            start = list(fixed = 
                                      c(Linf = 389.3647, 
                                        K = 0.4359, 
                                        t0 = -0.3127)),
                           method= "REML",
                           control=list(opt="nlminb",
                                        maxIter=100,
                                        pnlsMaxIter=100,
                                        msMaxIter=100,
                                        niterEM=100))
#save(nlme.mod, 
#     file = "Statistical-Analysis/Model-Output/nlme.mod.rda")
```


```{r Load nlme.mod, include=FALSE}
load("Statistical-Analysis/Model-Output/nlme.mod.rda")
```
```{r Results of nlme.mod, echo=FALSE}
print(paste("Iterations =", nlme.mod$numIter))
summary(nlme.mod)
intervals(nlme.mod)
anova(nlme.mod)
plot(nlme.mod)
```
```{r nlme.mod Plot and effects}
fixef(nlme.mod)
ranef(nlme.mod)
coef(nlme.mod)[1,3]
```


```{r}
Axes <- seq(100,450,by=50)
Years <- seq(0,8,by=1)

## plot individual fish data
## plot the fixed parameter model
## plot individual fish models

plot(jitter(LMBL$Agei),LMBL$BI.len,
     col=rgb(0,1,0,0.25, maxColorValue=1),
     pch=19,
     ylim=c(100,450),
     xlim=c(0,8),
     xlab = "Age (Years)",
     ylab = "Back-Calculated Length (mm)",
     bty="n",
     yaxt="n",
     xaxt="n")

axis(2,at = Axes)
axis(1,at = Years)

abline(h=425.6965204,lty=2)

x <- seq(1,8,by=1)
lines(x, fixef(nlme.mod)[1] * (1 - exp(-fixef(nlme.mod)[2] * (x - (fixef(nlme.mod)[3])))),
      lwd=3, 
      col="black")

for(i in 1:125){
lines(x, coef(nlme.mod)[i,1] * (1 - exp(- coef(nlme.mod)[i,2]   
* (x - ( coef(nlme.mod)[i,3] )))),lwd=3,col=gray(0,0.1)) }

legend("topleft",
       legend = print(expression(L[i]==422.17 %*% (1 - e **{-0.41 %*% (t[i] + 0.36)}))),
       bty="n",
       cex=1.15)

```

